apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dashy
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem
